name: "CI"

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  tests:
    name: "Run Tests"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "8.0"
          - "8.1"
          - "8.2"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: none
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1
          tools: composer:v2, cs2pr

      - name: "Cache dependencies"
        uses: "actions/cache@v2"
        with:
          path: |
            ~/.composer/cache
            vendor
          key: "php-${{ matrix.php-version }}"

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress --no-suggest"

      - name: "EasyCodingStandards for src"
        run: "vendor/bin/ecs check src tests --no-interaction --no-progress-bar"

      - name: "PhpStan for src"
        run: "vendor/bin/phpstan analyse --error-format=checkstyle src --level=8 | cs2pr"

      - name: "PhpStan for tests"
        run: "vendor/bin/phpstan analyse --error-format=checkstyle tests --level=6 | cs2pr"

      - name: "PHPUnit Test"
        run: "vendor/bin/phpunit tests/BaseTest.php"
